project_name: multi-teacher
model: /ssd4/lizijian/Models/Qwen3-4B
output_path: ./output/qwen3-4b-instruct-distill
use_flash_attention: true
sequence_length: 4096
model_kwargs:
  device_map: cuda:0

dataset:
  train_dataset:
    repo_id: /ssd4/lizijian/Datasets/allenai/tulu-3-sft-mixture
    split: train
  seed: 42

loss_functions:
  - function: cross_entropy
    weight: 0.5
  - function: kl
    weight: 0.5
    temperature: 2.0

teachers:
  - kind: hf
    path: /ssd4/lizijian/Models/Meta-Llama-3.1-8B-Instruct
    kwargs:
      attn_implementation: flash_attention_2
      torch_dtype: bfloat16
      device_map: cuda:1

training_args:
  dataset_text_field: text
  packing: True
  num_train_epochs: 1
  per_device_train_batch_size: 1
  gradient_accumulation_steps: 8
  save_steps: 200
  save_total_limit: 1
  logging_steps: 1
  learning_rate: 1.0e-5
  weight_decay: 0.05
  warmup_ratio: 0.025
  lr_scheduler_type: cosine
  bf16: true
  max_grad_norm: 0.5
  optim: paged_adamw_8bit
  gradient_checkpointing: true
  gradient_checkpointing_kwargs:
    use_reentrant: false
  report_to: wandb
  push_to_hub: false
  dataset_num_proc: 32
